Session auth
RIFT-tokyo/transcendence-docs pull request #10
Opened 2022-01-29 15:21 UTC by sasakiyudai

## チケットへのリンク
#7 

## やったこと
42 oauthで必要なAPI追加(/auth/login/42, /auth/callback/42)
Set-CookieやLocationなど必要なヘッダ追加

## やらないこと

## テスト
docsなので目視

## その他
Set-Cookieの説明でSecure属性をつけてますが、開発の際はつけないです。(dev中はhttps化してないため)
/auth/login/42 ... 下の画像の(1)
/auth/callback/42 ... 下の画像の(5)
![image](https://user-images.githubusercontent.com/66932739/151666488-de792e7e-f7bf-45ce-81c4-783d88566c19.png)

 
全体のイメージの参考: https://github.com/sasakiyudai/websocket-chat

2022-01-30 00:21 UTC, tkomatsu reviewed
swaggerで鍵マークがついて認証が必要であることがわかるようにセキュリティを作成してください。
全てのエンドポイントのヘッダーにcookieを設定するのはこれから増やすエンドポイントに対して全て行わなければならず、漏れが出る可能性が高いです。グローバルな設定をして不要な確認を減らしたいです。
![image](https://user-images.githubusercontent.com/46949817/151681840-5ea91054-09c5-491b-a64f-565468086863.png)
Security SchemeとGlobal Securityを設定すればできるはずです。
参考URL: https://swagger.io/docs/specification/authentication/cookie-authentication/

2022-01-30 00:36 UTC, tkomatsu commented
コールバックのエンドポイントを作成してフロントで処理する理由がいまいちわからんです。
認可コードをfrontに返す意味ってあるんですか？apiサーバに認可コードを返して、トークンを取得するまでapiの中だけで完結していいと思うのですが。
認証でユーザーが必要なのはログインする部分だけで、他は裏側で勝手にやればいいと思います。

2022-01-30 01:10 UTC, tkomatsu commented on openapi.yaml
> +  /auth/login/42:
tagつけて欲しいです。
`auth`とかかな

2022-01-30 01:10 UTC, tkomatsu commented on openapi.yaml
> +  /auth/callback/42:
tagつけて欲しいです

2022-01-30 04:27 UTC, sasakiyudai commented
> コールバックのエンドポイントを作成してフロントで処理する理由がいまいちわからんです。 認可コードをfrontに返す意味ってあるんですか？apiサーバに認可コードを返して、トークンを取得するまでapiの中だけで完結していいと思うのですが。 認証でユーザーが必要なのはログインする部分だけで、他は裏側で勝手にやればいいのでは？

自分もそう思ったのですが、いくら調べてもそういった例がなかったのでこのようになりました。
https://openid-foundation-japan.github.io/rfc6749.ja.html#:~:text=4.1.%C2%A0-,%E8%AA%8D%E5%8F%AF%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AB%E3%82%88%E3%82%8B%E8%AA%8D%E5%8F%AF,-%E8%AA%8D%E5%8F%AF%E3%82%B3%E3%83%BC%E3%83%89%E3%82%B0%E3%83%A9%E3%83%B3%E3%83%88
RFC的にも(A)と(D)のリクエストが同じところから生えているので、そしてredirect_urlというパラメータが用意されているので、こちらの方が自然かなと思いました。

> 添付された画像のClient Serverってtranscendenceで実装する部分ですか？
図のClient Serverはnestのサーバーに当たります。

2022-01-30 05:02 UTC, sasakiyudai commented on openapi.yaml
> +  /auth/callback/42:
done 5d9b028

2022-01-30 05:02 UTC, sasakiyudai commented on openapi.yaml
> +  /auth/login/42:
done 5d9b028

2022-01-30 05:29 UTC, sasakiyudai commented
> swaggerで鍵マークがついて認証が必要であることがわかるようにセキュリティを作成してください。

done 88ef6c9

2022-01-30 06:14 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
不要な部分消しておいてください

2022-01-30 06:14 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
消す

2022-01-30 06:14 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
消す

2022-01-30 06:14 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
消す

2022-01-30 06:14 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
消す

2022-01-30 06:14 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
消す

2022-01-30 06:15 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
消す

2022-01-30 06:15 UTC, tkomatsu commented on openapi.yaml
> +    parameters: []
消す

2022-01-30 06:15 UTC, tkomatsu commented on openapi.yaml
> +      security: []
消す

2022-01-30 06:15 UTC, tkomatsu commented on openapi.yaml
> +    parameters: []
消す

2022-01-30 06:24 UTC, tkomatsu commented
> 自分もそう思ったのですが、いくら調べてもそういった例がなかったのでこのようになりました。
RFC的にも(A)と(D)のリクエストが同じところから生えているので、そしてredirect_urlというパラメータが用意されているので、こちらの方が自然かなと思いました。

```
  +----------+
  | Resource |
  |   Owner  |
  |          |
  +----------+
       ^
       |
      (B)
  +----|-----+          Client Identifier      +---------------+
  |         -+----(A)-- & Redirection URI ---->|               |
  |  User-   |                                 | Authorization |
  |  Agent  -+----(B)-- User authenticates --->|     Server    |
  |          |                                 |               |
  |         -+----(C)-- Authorization Code ---<|               |
  +-|----|---+                                 +---------------+
    |    |                                         ^      v
   (A)  (C)                                        |      |
    |    |                                         |      |
    ^    v                                         |      |
  +---------+                                      |      |
  |         |>---(D)-- Authorization Code ---------'      |
  |  Client |          & Redirection URI                  |
  |         |                                             |
  |         |<---(E)----- Access Token -------------------'
  +---------+       (w/ Optional Refresh Token)
```
ここでは
User-Agent: front (ブラウザで実行されるコード)
Client: api
Authentication Server: 42 intra
Resource Owner: login user
になると思います。
OpenAPIで規定すべきものはあくまでUser-AgentとClientの間でのAPIの定義であり、それ以外の部分に関しては関与しません。つまり、(D)はtranscendenceのAPIサーバと42 APIサーバの間のやりとりであり、OpenAPIで定義すべきものではないのでは？

2022-01-30 06:31 UTC, tkomatsu commented
あと、エンドポイントのパスなんですが、
`/auth/login` とし、42を使うのかメールパスワードを使うのかなどはURLクエリで渡したほうがリソースが単純でいいんじゃないかなあと思いました。

2022-01-30 07:01 UTC, sasakiyudai commented
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:02 UTC, sasakiyudai commented
security: []
はauth/login のsecurityをオーバーライドしてsessionAuthスキーマを使用しないようにしてます。

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +      parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +      parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +      parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +      parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +      parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +      parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +      parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)

2022-01-30 07:03 UTC, sasakiyudai commented on openapi.yaml
> +    parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)
security: []
はauth/login のsecurityをオーバーライドしてsessionAuthスキーマを使用しないようにしてます。

2022-01-30 07:04 UTC, sasakiyudai commented on openapi.yaml
> +      security: []
security: []
はauth/login のsecurityをオーバーライドしてsessionAuthスキーマを使用しないようにしてます。

2022-01-30 07:04 UTC, sasakiyudai commented on openapi.yaml
> +    parameters: []
parameters: []
はstoplightで編集すると、自動的に追加されてしまうので毎回手動で消すのめんどくさいです(Ｔ＿Ｔ)
security: []
はauth/login のsecurityをオーバーライドしてsessionAuthスキーマを使用しないようにしてます。

2022-01-30 07:08 UTC, sasakiyudai commented
> ここでは
User-Agent: front (ブラウザで実行されるコード)
Client: api
Authentication Server: 42 intra
Resource Owner: login user
になると思います。
OpenAPIで規定すべきものはあくまでUser-AgentとClientの間でのAPIの定義であり、それ以外の部分に関しては関与しません。つまり、(D)はtranscendenceのAPIサーバと42 APIサーバの間のやりとりであり、OpenAPIで定義すべきものではないのでは？

2022-01-30 07:10 UTC, sasakiyudai commented
> あと、エンドポイントのパスなんですが、
/auth/login とし、42を使うのかメールパスワードを使うのかなどはURLクエリで渡したほうがリソースが単純でいいんじゃないかなあと思いました。

2fd83d8 で対応しました

2022-01-30 07:11 UTC, sasakiyudai commented
> ここでは
User-Agent: front (ブラウザで実行されるコード)
Client: api
Authentication Server: 42 intra
Resource Owner: login user
になると思います。
OpenAPIで規定すべきものはあくまでUser-AgentとClientの間でのAPIの定義であり、それ以外の部分に関しては関与しません。つまり、(D)はtranscendenceのAPIサーバと42 APIサーバの間のやりとりであり、OpenAPIで定義すべきものではないのでは？

確かに、そうなのかもしれないですね。callbackのpathは消しました。

2022-01-30 07:16 UTC, tkomatsu commented on openapi.yaml
> +      parameters: []
できればgitにaddするときはadd -p して欲しいです。
最終的に見るのはコードであって、その途中のツールではないので。

2022-01-30 07:16 UTC, tkomatsu commented on openapi.yaml
> +    parameters: []
securityの部分は理解です！

2022-01-30 07:16 UTC, tkomatsu commented on openapi.yaml
> +      security: []
理解

2022-01-30 07:18 UTC, tkomatsu commented on openapi.yaml
> +    parameters: []
spotlightで編集したとしてもcommitするときはターミナルとかVSCodeではないの？
最終的にコミットするときに変更内容を確認した上でコミットして欲しいです。

2022-01-30 07:20 UTC, tkomatsu commented
(D)のエンドポイントは不要だと思うんだけど、(C)のエンドポイントはいるのかも？
図の認証を始めるためのエンドポイント（(A)を返すためのエンドポイント）と、(C)に対応するためのエンドポイントは必要かもしれないと思ったり。

2022-01-30 07:34 UTC, sasakiyudai commented
・parameters: []について
swagger.ymlをymlで見る人あまりいないと思うので、swagger ui上で支障ないものは別に消す必要ないと思います。

・(C)のエンドポイントについて
https://qiita.com/TakahikoKawasaki/items/8567c80528da43c7e844#:~:text=%E8%A8%80%E3%81%84%E3%81%BE%E3%81%99%E3%80%82-,%E8%AA%8D%E5%8F%AF%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B9%E3%81%AF%E3%83%AA%E3%83%80%E3%82%A4%E3%83%AC%E3%82%AF%E3%83%88%E3%82%92%E7%99%BA%E7%94%9F%E3%81%95%E3%81%9B%E3%82%8B,-%E8%AA%8D%E5%8F%AF%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B9%E3%82%92
よもやこれがcallbackな気がします。

2022-01-30 11:41 UTC, tkomatsu commented
endpointの設計の話で、パスパラメータではなくクエリパラメータの方がいいのではと言う提案をしたつもりでした！/auth/login/{provider} ではなく/auth/login でクエリパラメータに?provider=42 とか?username=test&password=12345678 みたいに渡すってことを伝えたかった。
リソースとしてはあくまで認証用のリソースであり、認証のために必要な情報はクエリパラメータで渡すという意図でした。クエリパラメータで渡すメリットとしてはデフォルトの認証方法が定義できることです。クエリパラメータがなければintra認証を使い、パスワードが渡されたら独自認証をするといったようにです。

2022-02-01 13:00 UTC, tkomatsu requested changes
認証系のエラー定義を今あるエンドポイントに併せて追加してほしいです。

2022-02-01 13:00 UTC, tkomatsu commented on openapi.yaml
> +      responses:
500のサーバー側のエラーはいらないです？

2022-02-01 13:00 UTC, tkomatsu commented on openapi.yaml
> +      responses:
500はなくてもよいの？

2022-02-01 13:00 UTC, tkomatsu commented on openapi.yaml
> +  /auth/callback:
500はなくてもよいの？

2022-02-01 13:00 UTC, tkomatsu commented on openapi.yaml
> +      required: true
providerってマストで必要？デフォルトは42認証になるからいらない気がする。
そして、Google認証を追加しない場合はそもそもproviderはなくてもいいのかも。

2022-02-01 13:00 UTC, tkomatsu commented on openapi.yaml
> +    SimpleLoginUser:
POST /auth/login でしか使わないからSchema定義しなくてもいいのかもと思うけど、コード生成がうまくできないならあったほうがいいのかな。
名前は`UserLogin`とかの方がいい気がする。何がSimpleなんだ？って思った。

2022-02-01 13:20 UTC, sasakiyudai commented on openapi.yaml
> +    SimpleLoginUser:
d1704eb けしました　

2022-02-01 13:20 UTC, sasakiyudai commented on openapi.yaml
> +      required: true
d1704eb けしました

2022-02-01 13:20 UTC, sasakiyudai commented on openapi.yaml
> +  /auth/callback:
d1704eb　たしました

2022-02-01 13:20 UTC, sasakiyudai commented on openapi.yaml
> +      responses:
d1704eb　たしました

2022-02-01 13:20 UTC, sasakiyudai commented on openapi.yaml
> +      responses:
d1704eb　たしました

2022-02-01 13:32 UTC, tkomatsu commented on openapi.yaml
> +          content:
リダイレクトレスポンスにボディいります？

2022-02-01 15:26 UTC, sasakiyudai commented on openapi.yaml
> +          content:
いらないのでけしました　8babd14

2022-02-02 10:58 UTC, tkomatsu requested changes
エラーレスポンス時にError Schemeをボディに含めてほしいです。

2022-02-02 11:38 UTC, tkomatsu requested changes

2022-02-02 11:38 UTC, tkomatsu commented on openapi.yaml
> +        '500':
Error Schemeを返してください

2022-02-02 11:38 UTC, tkomatsu commented on openapi.yaml
> +        '400':
Error Schemeを返してください

2022-02-02 11:38 UTC, tkomatsu commented on openapi.yaml
> +        '500':
Error Schemeを返してください

2022-02-02 11:38 UTC, tkomatsu commented on openapi.yaml
> +        '500':
Error Schemeを返してください

2022-02-02 11:44 UTC, tkomatsu approved these changes

2022-02-02 11:44 UTC, merged