async api
RIFT-tokyo/transcendence-docs pull request #20
Opened 2022-03-29 14:04 UTC by sasakiyudai

## チケットへのリンク
使用決め　ステータス
## やったこと
async api
## やらないこと

## テスト

## その他

2022-03-30 11:48 UTC, tkomatsu requested changes

2022-03-30 11:48 UTC, tkomatsu commented on asyncapi.yml
> +    url: localhost:4214
localhost:4210にしておいてください
envのport変更のPRだけ先に出すようにします

2022-03-30 11:48 UTC, tkomatsu commented on asyncapi.yml
> +  /:
channnelsはOpenAPIでいうところのエンドポイントだと思うので、用途ごとにchannelを作成してください

2022-03-30 11:48 UTC, tkomatsu commented on asyncapi.yml
> +    status:
statusを分けてスキーマ定義してるのってなんでです？

2022-03-30 11:48 UTC, tkomatsu commented on asyncapi.yml
> +      description: authentication token for private-data endpoints.
細かいですが、EOFに改行つけといてください

2022-03-30 11:48 UTC, tkomatsu commented on asyncapi.yml
> +      x-response:
x-responseってなんです？
pingにだけついてる理由とそもそもの用途知りたいです

2022-03-31 13:44 UTC, sasakiyudai commented on asyncapi.yml
> +      x-response:
元々あるresponseを拡張したものです。https://www.asyncapi.com/blog/websocket-part2#:~:text=You%20can%20extend,called%20x%2Dresponse.
pingをpubするとpongが帰ってきます。

2022-03-31 13:44 UTC, sasakiyudai commented on asyncapi.yml
> +      description: authentication token for private-data endpoints.
done [61ed1ab](https://github.com/RIFT-tokyo/transcendence-docs/pull/20/commits/61ed1abf7e5909373567f7270eba1288b3d69f2e)

2022-03-31 13:45 UTC, sasakiyudai commented on asyncapi.yml
> +    status:
statusを複数箇所で使ってた名残りです。今は複数じゃないので直しました。[61ed1ab](https://github.com/RIFT-tokyo/transcendence-docs/pull/20/commits/61ed1abf7e5909373567f7270eba1288b3d69f2e)

2022-03-31 13:45 UTC, sasakiyudai commented on asyncapi.yml
> +  /:
fix [61ed1ab](https://github.com/RIFT-tokyo/transcendence-docs/pull/20/commits/61ed1abf7e5909373567f7270eba1288b3d69f2e)

2022-03-31 13:45 UTC, sasakiyudai commented on asyncapi.yml
> +    url: localhost:4214
done [61ed1ab](https://github.com/RIFT-tokyo/transcendence-docs/pull/20/commits/61ed1abf7e5909373567f7270eba1288b3d69f2e)

2022-04-02 05:44 UTC, tkomatsu requested changes

2022-04-02 05:44 UTC, tkomatsu commented on asyncapi.yml
> +          - $ref: '#/components/messages/ping'
ping/pongって全体のヘルスチェックではないのですか？
/usersに含めるのって何か理由があるのでしょうか？

2022-04-05 09:18 UTC, sasakiyudai commented on asyncapi.yml
> +          - $ref: '#/components/messages/ping'
理由はないです。移動しました。
[26e6ae4](https://github.com/RIFT-tokyo/transcendence-docs/pull/20/commits/26e6ae4a0598ee377e6e6b4371f9038d585455e3)

2022-04-05 10:55 UTC, tkomatsu commented on asyncapi.yml
> +          $ref: '#/components/schemas/username'
ping/pongが/usersから外れたのであれば、ping/pongのスキーマにusernameを含めなくていいのでは？
usernameを含めると意味のあるものに思えるのですが、単に`ping`という文字列を送ったら`pong`という文字列が返って来るみたいな感じでもいいのでは？

2022-04-05 11:18 UTC, sasakiyudai commented on asyncapi.yml
> +          $ref: '#/components/schemas/username'
done [8d4c21b](https://github.com/RIFT-tokyo/transcendence-docs/pull/20/commits/8d4c21b29a765516f3933ec10795714bfeea056e)

2022-04-05 11:47 UTC, tkomatsu approved these changes

2022-04-05 11:48 UTC, tkomatsu commented
LGTM!

2022-04-05 11:48 UTC, merged